CREATE DATABASE CollegeDB;
USE CollegeDB;
CREATE TABLE Department (
    DepartmentID INT(10) PRIMARY KEY,
    DepartmentName VARCHAR(20),
    HOD VARCHAR(20) NOT NULL);
DESC DEPARTMEANT ;
INSTAL DEPARTMEANT VALUES ("101","ADITH","JAYANTHI");
SELECT*FROM DEPARTMEANT;
DESC DEPARTMEANT ;
